// frontend/src/components/home/PromoBanner.jsx
import React from 'react';
import './PromoBanner.css';

const MONOLITH_BASE = import.meta.env.VITE_MONOLITH_URL || 'http://localhost/angelow';

const PromoBanner = ({ banner }) => {
    if (!banner) return null;

    const hasImage = !!banner.image;
    const bgStyle = hasImage
        ? { backgroundImage: `url('${MONOLITH_BASE}/${banner.image}')` }
        : {};

    return (
        <section className={`promo-banner ${hasImage ? 'has-image' : ''}`} style={bgStyle}>
            {hasImage && <div className="promo-image-overlay" />}
            <div className="promo-content">
                {banner.icon && <i className={`fas ${banner.icon} fa-3x`} />}
                <h2>{banner.title}</h2>
                {banner.subtitle && <p>{banner.subtitle}</p>}
                {banner.button_text && banner.button_link && (
                    <a href={banner.button_link} className="btn">{banner.button_text}</a>
                )}
            </div>
        </section>
    );
};

export default PromoBanner;

// frontend/src/modules/home/components/PromoBanner.vue
<template>
  <section
    v-if="banner"
    class="promo-banner"
    :class="{ 'has-image': Boolean(banner.image) }"
    :style="bannerStyle"
  >
    <div v-if="banner.image" class="promo-image-overlay" />
    <div class="promo-content">
      <i v-if="banner.icon" class="fas" :class="banner.icon" />
      <h2>{{ banner.title || 'Promocion especial' }}</h2>
      <p>{{ banner.subtitle || banner.message }}</p>
      <RouterLink class="btn" :to="{ name: 'store' }">
        {{ banner.button_text || 'Ver promociones' }}
      </RouterLink>
    </div>
  </section>
</template>

<script setup>
import { computed } from 'vue'
import { RouterLink } from 'vue-router'
import { resolveMediaUrl } from '../../../utils/media'

const props = defineProps({
  banner: {
    type: Object,
    default: null,
  },
})

const bannerStyle = computed(() => {
  if (!props.banner?.image) return {}
  return {
    backgroundImage: `url('${resolveMediaUrl(props.banner.image, '/logo_principal.png')}')`,
  }
})
</script>
